# Version 3

language: c

cache:
  - apt

# we're building only stuff pushed into "travis" branch
branches:
  only:
    - travis

install:
  - sudo apt-get install -qq build-essential gcc-arm-linux-gnueabihf bc

  # add some Ubuntu Trusty packages - we require device-tree-compiler >= 1.4
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
  - sudo apt-get update -q
  - sudo apt-get install -qq device-tree-compiler

script:
  - make CROSS_COMPILE=arm-linux-gnueabihf- A20-OLinuXino_MICRO_config
  - make -j CROSS_COMPILE=arm-linux-gnueabihf-

addons:
  artifacts:
    paths:
      - spl/sunxi-spl.bin
      - u-boot.bin
      - u-boot.srec
      - u-boot.img
      - u-boot-sunxi-with-spl.bin
    debug: true
