# Version 5

language: c

cache:
  - apt

# we're building only stuff pushed into "travis" branch
branches:
  only:
    - travis
    - /^wb-.*$/

# Identify the build and construct artifact upload path
before_install:
  - export WB_PROJECT="watermelon"
  - export WB_REPO="u-boot"
  - export ARTIFACTS_TARGET_PATHS="commits/$WB_PROJECT/$WB_REPO/$TRAVIS_JOB_NUMBER"
  - if [ -n "$TRAVIS_TAG" ]; then export ARTIFACTS_TARGET_PATHS="stable/$WB_PROJECT/$WB_REPO/$TRAVIS_TAG"; fi
  - 'echo "Upload path=$ARTIFACTS_TARGET_PATHS; travis tag=$TRAVIS_TAG"'

install:
  - sudo apt-get install -qq build-essential gcc-arm-linux-gnueabihf bc

  # add some Ubuntu Trusty packages - we require device-tree-compiler >= 1.4
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
  - sudo sh -c "echo 'deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted' >/etc/apt/sources.list.d/trusty.list"
  - sudo apt-get update -q
  - sudo apt-get install -qq device-tree-compiler

script:
  - make CROSS_COMPILE=arm-linux-gnueabihf- A20-OLinuXino_MICRO_config
  - make -j CROSS_COMPILE=arm-linux-gnueabihf-

addons:
  artifacts:
    paths:
      - spl/sunxi-spl.bin
      - u-boot.bin
      - u-boot.srec
      - u-boot.img
      - u-boot-sunxi-with-spl.bin
    debug: true
    max-size: 262144000
