# Version 3

language: c

cache:
  - apt

# we're building only stuff pushed into "travis" branch
branches:
  only:
    - travis

install:
  - sudo apt-get install -qq build-essential gcc-arm-linux-gnueabihf bc

script:
  - make CROSS_COMPILE=arm-linux-gnueabihf- A20-OLinuXino_MICRO_config
  - make -j CROSS_COMPILE=arm-linux-gnueabihf-

addons:
  artifacts:
    paths:
      - spl/sunxi-spl.bin
      - u-boot.bin
      - u-boot.srec
      - u-boot.img
      - u-boot-sunxi-with-spl.bin
    debug: true
